export const data = {
  AllData: [
    {
      id: "Armor1",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "WEAPON_ASSAULTRIFLE",
    },
    {
      id: "Armor2",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "softvest",
    },
    {
      id: "Armor3",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "softvest",
    },
    {
      id: "Armor4",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "softvest",
    },
    {
      id: "Armor5",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "softvest",
    },
  ],
  Armor: [
    {
      id: "Armor1",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "softvest",
    },
    {
      id: "Armor2",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "softvest",
    },
    {
      id: "Armor3",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "softvest",
    },
    {
      id: "Armor4",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "softvest",
    },
    {
      id: "Armor5",
      name: "Soft Armor",
      effect: "50%",
      price: "500",
      ImageName: "/vest2.png",
      itemName: "softvest",
    },
  ],
};
